### ISSUE TITLE
函数notEncrypted中的bug

### ISSUE THREAD

**Issue by xbduan** [ZZMarquis/gm#1]
函数notEncrypted有个bug，请看有注释的行：
func notEncrypted(encData []byte, in []byte) bool {
	encDataLen := len(encData)
	for i := 0; i != encDataLen; i++ {
		if encData[i] != in[i] {  //，这一行的作用为判断t的每一字节是否为0，原来这一行为if encData[i] != in[0]，把0改为i就对了
			return false
		}
	}
	return true
}

**Comment by ZZMarquis** [comment]
对的！感谢指正！
