### ISSUE TITLE
sm2 Decrypt

### ISSUE THREAD

**Issue by yanghe1994** [ZZMarquis/gm#15]
请教下，我把加密卡导出的公钥和私钥传入sm2.RawBytesToPublicKey 和  sm2.RawBytesToPrivateKey ，sm2.Decrypt 时报错invalid cipher text 是什么原因了...

**Comment by ZZMarquis** [comment]
可能加密卡里导出来的是标准的DER编码的公钥和私钥。
sm2.RawBytesToPublicKey 和 sm2.RawBytesToPrivateKey不是用来转换DER编码公私钥的，是用来转纯字节数组的，即公钥的X和Y分量的32*2字节，和私钥的32字节。你可以看下如果加密卡导出的公钥大于65个字节，那么他应该是DER编码的公钥，同理如果私钥大于32个字节也是。
