### ISSUE TITLE
问题 关于公钥的 X, Y 如何生成  pem文件的字符串

### ISSUE THREAD

**Issue by ZRothschild** [ZZMarquis/gm#16]
我现在有这样的一个任务。就是用对方生成的sm2 公私钥。私钥是压缩格式，base64 . 
### 如果我使用的时候压缩的公钥，你这边使用什么验签函数去，验签呢？当然我可以转换再验签

**Comment by ZZMarquis** [comment]
1、SM2签名算法，就算你每次使用的私钥和源数据都一样，签名结果也不相同，因为签名过程有随机数参与，所以不用比较两个签名函数返回的结果是否相同。而应该去验证你们之间是否能互相验签成功。
2、目前这个项目没有做压缩公钥的验签，你需要先把公钥转换成非压缩。

**Comment by ZRothschild** [comment]
谢谢你的帮助。我明白了。只能验签，不能对比。我之前搞rsa 都是对比的





------------------ 原始邮件 ------------------
发件人: ZZMarquis ***@***.***&gt;
发送时间: 2021年6月10日 17:28
收件人: ZZMarquis/gm ***@***.***&gt;
抄送: ZRothschild ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[ZZMarquis/gm] 问题 关于公钥的 X, Y 如何生成  pem文件的字符串 (#16)





 
1、SM2签名算法，就算你每次使用的私钥和源数据都一样，签名结果也不相同，因为签名过程有随机数参与，所以不用比较两个签名函数返回的结果是否相同。而应该去验证你们之间是否能互相验签成功。
 2、目前这个项目没有做压缩公钥的验签，你需要先把公钥转换成非压缩。

**Comment by ZRothschild** [comment]
谢谢明白了





------------------ 原始邮件 ------------------
发件人: ZZMarquis ***@***.***&gt;
发送时间: 2021年6月10日 17:28
收件人: ZZMarquis/gm ***@***.***&gt;
抄送: ZRothschild ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[ZZMarquis/gm] 问题 关于公钥的 X, Y 如何生成  pem文件的字符串 (#16)





 
1、SM2签名算法，就算你每次使用的私钥和源数据都一样，签名结果也不相同，因为签名过程有随机数参与，所以不用比较两个签名函数返回的结果是否相同。而应该去验证你们之间是否能互相验签成功。
 2、目前这个项目没有做压缩公钥的验签，你需要先把公钥转换成非压缩。
