### ISSUE TITLE
sm2签名在gmssl服务端验证失败

### ISSUE THREAD

**Issue by glfov** [ZZMarquis/gm#17]
用此代码中的sm2 sign方法签名国密建链过程中的certificate verify消息，服务端是gmssl，针对该条消息服务端返回decrypt error错误，根据错误码查看gmssl代码是签名校验的时候失败了，想问下作者有类似场景的对接吗？可能的问题是什么？我之前用过tjfoc的gmsm库也有此问题

**Comment by ZZMarquis** [comment]
这类问题比较常见的是两端数据结构没对上。你们那个服务端要求的签名格式是咋样的？
