### ISSUE TITLE
针对sm2.Verify的cpu性能问题，有提升方案吗

### ISSUE THREAD

**Issue by duxin40** [ZZMarquis/gm#19]
![image](https://user-images.githubusercontent.com/33946910/200730212-afefafb9-fd9a-4d32-b3c8-a12f10e3a028.png)
如图，我们在压测时，发现sm2.Verify方法非常耗cpu，导致了性能瓶颈，请问针对这个问题有优化么

**Comment by hyfree** [comment]
有具体的性能测试数据吗，
处理器型号：
密钥对产生速度：每秒多少个
加密速率(4KB)：每秒多少次
解密速度(4KB)：每秒多少次
签名速度(4KB)：每秒多少次
验签速度(4KB)：每秒多少次

**Comment by gyf19** [comment]
可以考虑， 把go代码编译成 汇编代码。
