### ISSUE TITLE
为什么会出现 data[0] != 4 这个问题

### ISSUE THREAD

**Issue by Guanzi233** [ZZMarquis/gm#23]
补充一下前提：这是对接对方的api，我不知道对方的公钥，只有其给我的私钥，曲线也正常生成，对比了demo，曲线也是一致，但调用 sm2.Decrypt 这个函数时，程序则会产生崩溃。

![错误报错](https://user-images.githubusercontent.com/45566267/231731501-1d85281f-a6cb-4638-8a4c-fcb0a4157f35.png)
![错误位置](https://user-images.githubusercontent.com/45566267/231731523-b7c3be3c-7e74-4111-8f4e-f537f6122d37.png)

**Comment by ZZMarquis** [comment]
这个是因为这个接口要求的ECC点的格式是非压缩的格式：第一个字节是4表示不压缩。国密的文档里要求的应该就是不压缩，第一个字节应该就是4。
参考附录C：https://github.com/guanzhi/GM-Standards/blob/master/GMT%E5%AF%86%E7%A0%81%E8%A1%8C%E6%A0%87/GMT%200003.5-2012%20SM2%E6%A4%AD%E5%9C%86%E6%9B%B2%E7%BA%BF%E5%85%AC%E9%92%A5%E5%AF%86%E7%A0%81%E7%AE%97%E6%B3%95%E7%AC%AC5%E9%83%A8%E5%88%86%EF%BC%9A%E5%8F%82%E6%95%B0%E5%AE%9A%E4%B9%89.pdf
