### ISSUE TITLE
sign/verify结果输出问题

### ISSUE THREAD

**Issue by knull-cn** [ZZMarquis/gm#4]
我个人建议，你sign就生成两个big.Int(r/s)，至于编码，完全可以调用者自己来决定用哪种方式。毕竟，你已经提供了MarshalSign/UnmarshalSign两个函数了。
附注：我这边不需要用ans1编码，直接r/s用bytes拼接下就可以了（类似于公钥）。所以，我现在sign之后，需要先UnmarshalSign获得r/s，然后再进行bytes拼接。

**Comment by ZZMarquis** [comment]
加了两个方法
