### ISSUE TITLE
sm2验签偶发性失败

### ISSUE THREAD

**Issue by knull-cn** [ZZMarquis/gm#5]
测试描述：

    前置条件：相同的私钥，相同的数据，相同的公钥；

    测试内容：私钥对数据签名，公钥进行验签

    测试结果：偶发性的验签失败

**Comment by knull-cn** [comment]
我请教了下“梧桐链”的开发者，他们给了点方向、建议，如下：

1. 初步的判断是跟签名时使用的随机数有关
2. 机数过大使得签名或验签过程中求值溢出了
3. 多注意下签名与验签流程中的求值取余mod操作，以及大数的正负情况

**Comment by ZZMarquis** [comment]
请问你的公私钥是怎么生成的？
我写了点循环测试代码，没有测出来这个问题。

**Comment by knull-cn** [comment]
本身的循环测试，是没发现问题的（我测试了100万次，跑了24小时）
但是，在现实业务场景中，偶尔会发送验签失败的情况

**Comment by ZZMarquis** [comment]
那就不好排查了，要不你们可以试一下签名刚产生时就验签一下。主要是想看看有没有可能是数据或签名在传输流转过程中被改变了。

**Comment by ZZMarquis** [comment]
这个问题你们有线索了吗？

**Comment by knull-cn** [comment]
不好意思，最近没搞这个事情（其实是放弃了。。。）
没有特别的线索

**Comment by bjwswang** [comment]
@ZZMarquis  我最近用同济的国密库，也发现类似的问题。
情况是这样的：
1） 每次都创建ca 证书，以及使用ca证书签发子证书
2）子证书验签失败
这个过程是偶尔发生的。
有什么想法吗？

**Comment by xuxujie** [comment]
大佬们, 有新发现.
r, s, err := sm2.SignToRS(pri, nil, msg)
if err != nil {
	return "", err
}
hexSign := fmt.Sprintf("%x", r) + fmt.Sprintf("%x", s)
sm3摘要做了略微调整, 没有加盐, 直接使用原文摘要的.
发现结果偶尔是127位的(大部分时候是128位). 大佬请看一下.
