### ISSUE TITLE
Java端SM2加密，golang无法解密，golang端SM2加密，java无法解密

### ISSUE THREAD

**Issue by linxueyi2230** [ZZMarquis/gm#6]
golang端用的国密算法库是：https://github.com/ZZMarquis/gm
java端用的国密算法库是：https://github.com/gotoworld/hsd-cipher-sm

经过测试后发现：Java端SM2加密，golang无法解密，golang端SM2加密，java无法解密
排查了很久搜索到一篇文章讲解了不同点：https://my.oschina.net/u/2539854/blog/3094186

**Comment by ZZMarquis** [comment]
嗯，之前已经修复了这个问题。注意选择一样的模式即可：golang和Java端都选择C1C2C3或C1C3C2。
