### ISSUE TITLE
sigtopub

### ISSUE THREAD

**Issue by caoliangccut20121192** [ZZMarquis/gm#7]
能根据签名和hash恢复出公钥吗

**Comment by ZZMarquis** [comment]
hash指什么的hash？

**Comment by caoliangccut20121192** [comment]
就是国密把公钥X，和公钥Y全hash方法

**Comment by caoliangccut20121192** [comment]
e := calculateE(digest, &priv.Curve, pubX, pubY, userId, in) 假如我知道这个值，是否可以恢复公钥

**Comment by ZZMarquis** [comment]
你是说知道e，能不能把pubX和pubY反推出来？
我觉得是不行的，hash算法是不可逆的。

**Comment by caoliangccut20121192** [comment]
你写的那个签名r和s出来有时候为什么是31字节啊

**Comment by ZZMarquis** [comment]
R和S实际都是一个大数，如果恰巧是一个较小的数转成字节数组时就有可能是31字节，如果你需要32字节，在前面再加上一个字节就行。
