### ISSUE TITLE
sm2进行加解密时，建议对公钥的X和Y的[]byte类型进行填充

### ISSUE THREAD

**Issue by tkblack** [ZZMarquis/gm#9]
最近在进行加解密时，发现和java进行联调时偶尔出现无法解密的情况，然后对比下和java代码里面国密库的实现，发现java中加密过程中会对公钥的x和y值进行填充，但是这里并没有，而是直接使用`c1x.Bytes()`方法，这样就导致c1x值比较小时，得到的切片长度小于32，文件sm2/sm2.go， 如第217行我增加了填充处理： `c1xBytes = append(make([]byte, 32-len(c1xBytes)), c1xBytes...)`（c1yBytes也做同样的处理）；另外，`Encrypt`和`Decrypt`中也需要同样处理。

**Comment by ZZMarquis** [comment]
@tkblack 好的，感谢建议
